common/urls.py
from django.urls import path
from .views import *

app_name = "common"
urlpatterns = [path("", home), path("home/", home, name="home")]

group/urls.py
from django.urls import path
from group.views import *
from group.feeds import LatestTopicsFeed
from django.contrib.auth.decorators import login_required


app_name = "group"
urlpatterns = [
    path("create/", login_required(create), name="create"),
    path("<int:group_id>/new_topic", login_required(new_topic), name="new_topic"),
    path("<int:group_id>/join", j_login_required(join), name="join"),
    path("<int:group_id>/leave", j_login_required(leave), name="leave"),
    path("<int:group_id>/group_edit", login_required(group_edit), name="group_edit"),
    path("<int:group_id>/topics", get_topics, name="topics"),
    path("<int:group_id>/", group, name="group"),
    path("topic/<int:topic_id>/", topic, name="topic"),
    path("topic/<int:topic_id>/comments", get_comments, name="comments"),
    path("topic/<int:topic_id>/delete", delete_topic, name="delete_topic"),
    path("comment/<int:comment_id>/delete", delete_comment, name="delete_comment"),
    path("comment/<int:comment_id>/like", j_login_required(like_comment), name="like_comment"),
    path("profile/<str:mastodon_username>/", profile, name="profile"),
    path("<int:group_id>/feed/", LatestTopicsFeed(), name="feed"),
]

neogroup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from users.views import login

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", login),
    path("markdownx/", include("markdownx.urls")),
    path("users/", include("users.urls")),
    path("group/", include("group.urls")),
    path("", include("common.urls")),
    path("tz_detect/", include("tz_detect.urls")),
]

# if settings.DEBUG:
    # from django.conf.urls.static import static
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path("login/", login, name="login"),
    path("register/", register, name="register"),
    path("connect/", connect, name="connect"),
    path("reconnect/", reconnect, name="reconnect"),
    path("data/", data, name="data"),
    path("data/sync_mastodon", sync_mastodon, name="sync_mastodon"),
    path("data/clear_data", clear_data, name="clear_data"),
    path("logout/", logout, name="logout"),
    path("layout/", set_layout, name="set_layout"),
    path("OAuth2_login/", OAuth2_login, name="OAuth2_login"),
    path("<str:id>/followers/", followers, name="followers"),
    path("<str:id>/following/", following, name="following"),
    path("report/", report, name="report"),
    path("manage_report/", manage_report, name="manage_report"),
]

common/forms.py
from django import forms
from markdownx.fields import MarkdownxFormField
from django.utils import formats
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import json


class KeyValueInput(forms.Widget):
    """
    Input widget for Json field
    """

    template_name = "widgets/hstore.html"

    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        data = None
        if context["widget"]["value"] is not None:
            data = json.loads(context["widget"]["value"])
        context["widget"]["value"] = (
            [{p[0]: p[1]} for p in data.items()] if data else []
        )
        return context

    class Media:
        js = ("js/key_value_input.js",)


class HstoreInput(forms.Widget):
    """
    Input widget for Hstore field
    """

    template_name = "widgets/hstore.html"

    def format_value(self, value):
        """
        Return a value as it should appear when rendered in a template.
        """
        if value == "" or value is None:
            return None
        if self.is_localized:
            return formats.localize_input(value)
        # do not return str
        return value

    class Media:
        js = ("js/key_value_input.js",)


class JSONField(forms.fields.JSONField):
    widget = KeyValueInput

    def to_python(self, value):
        if not value:
            return None
        j = {}
        if isinstance(value, dict):
            j = value
        else:
            pairs = json.loads("[" + value + "]")
            if isinstance(pairs, dict):
                j = pairs
            else:
                # list or tuple
                for pair in pairs:
                    j = {**j, **pair}
        return super().to_python(j)


class RadioBooleanField(forms.ChoiceField):
    widget = forms.RadioSelect

    def to_python(self, value):
        """Return a Python boolean object."""
        # Explicitly check for the string 'False', which is what a hidden field
        # will submit for False. Also check for '0', since this is what
        # RadioSelect will provide. Because bool("True") == bool('1') == True,
        # we don't need to handle that explicitly.
        if isinstance(value, str) and value.lower() in ("false", "0"):
            value = False
        else:
            value = bool(value)
        return value


class RatingValidator:
    """empty value is not validated"""

    def __call__(self, value):
        if not isinstance(value, int):
            raise ValidationError(
                _("%(value)s is not an integer"),
                params={"value": value},
            )
        if not str(value) in [str(i) for i in range(0, 11)]:
            raise ValidationError(
                _("%(value)s is not an integer in range 1-10"),
                params={"value": value},
            )


class PreviewImageInput(forms.FileInput):
    template_name = "widgets/image.html"

    def format_value(self, value):
        """
        Return the file object if it has a defined url attribute.
        """
        if self.is_initial(value):
            if value.url:
                return value.url
            else:
                return

    def is_initial(self, value):
        """
        Return whether value is considered to be initial value.
        """
        return bool(value and getattr(value, "url", False))


class TagInput(forms.TextInput):
    """
    Dump tag queryset into tag list
    """

    template_name = "widgets/tag.html"

    def format_value(self, value):
        if value == "" or value is None or len(value) == 0:
            return ""
        tag_list = []
        try:
            tag_list = [t["content"] for t in value]
        except TypeError:
            tag_list = [t.content for t in value]
        # return ','.join(tag_list)
        return tag_list

    class Media:
        css = {"all": ("lib/css/tag-input.css",)}
        js = ("lib/js/tag-input.js",)


class TagField(forms.CharField):
    """
    Split comma connected string into tag list
    """

    widget = TagInput

    def to_python(self, value):
        value = super().to_python(value)
        if not value:
            return
        return [t.strip() for t in value.split(",")]


class MultiSelect(forms.SelectMultiple):
    template_name = "widgets/multi_select.html"

    class Media:
        css = {
            "all": (
                "https://cdn.jsdelivr.net/npm/multiple-select@1.5.2/dist/multiple-select.min.css",
            )
        }
        js = (
            "https://cdn.jsdelivr.net/npm/multiple-select@1.5.2/dist/multiple-select.min.js",
        )


class HstoreField(forms.CharField):
    widget = HstoreInput

    def to_python(self, value):
        if not value:
            return None
        # already in python types
        if isinstance(value, list):
            return value
        pairs = json.loads("[" + value + "]")
        return pairs


class DurationInput(forms.TextInput):
    """
    HH:mm:ss input widget
    """

    input_type = "time"

    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        # context['widget']['type'] = self.input_type
        context["widget"]["attrs"]["step"] = "1"
        return context

    def format_value(self, value):
        """
        Given `value` is an integer in ms
        """
        ms = value
        if not ms:
            return super().format_value(None)
        x = ms // 1000
        seconds = x % 60
        x //= 60
        if x == 0:
            return super().format_value(f"00:00:{seconds:0>2}")
        minutes = x % 60
        x //= 60
        if x == 0:
            return super().format_value(f"00:{minutes:0>2}:{seconds:0>2}")
        hours = x % 24
        return super().format_value(f"{hours:0>2}:{minutes:0>2}:{seconds:0>2}")


class DurationField(forms.TimeField):
    widget = DurationInput

    def to_python(self, value):

        # empty value
        if value is None or value == "":
            return

        # if value is integer in ms
        if isinstance(value, int):
            return value

        # if value is string in time format
        h, m, s = value.split(":")
        return (int(h) * 3600 + int(m) * 60 + int(s)) * 1000


#############################
# Form
#############################
VISIBILITY_CHOICES = [
    (0, _("公开")),
    (1, _("仅关注者")),
    (2, _("仅自己")),
]


class MarkForm(forms.ModelForm):
    id = forms.IntegerField(required=False, widget=forms.HiddenInput())
    share_to_mastodon = forms.BooleanField(
        label=_("分享到联邦网络"), initial=True, required=False
    )
    rating = forms.IntegerField(
        label=_("评分"),
        validators=[RatingValidator()],
        widget=forms.HiddenInput(),
        required=False,
    )
    visibility = forms.TypedChoiceField(
        label=_("可见性"),
        initial=0,
        coerce=int,
        choices=VISIBILITY_CHOICES,
        widget=forms.RadioSelect,
    )
    tags = TagField(
        required=False,
        widget=TagInput(attrs={"placeholder": _("回车增加标签")}),
        label=_("标签"),
    )
    text = forms.CharField(
        required=False,
        widget=forms.Textarea(
            attrs={"placeholder": _("最多只能写360字哦~"), "maxlength": 360}
        ),
        label=_("短评"),
    )


class ReviewForm(forms.ModelForm):
    title = forms.CharField(label=_("标题"))
    content = MarkdownxFormField(label=_("正文 (Markdown)"))
    share_to_mastodon = forms.BooleanField(
        label=_("分享到联邦网络"), initial=True, required=False
    )
    id = forms.IntegerField(required=False, widget=forms.HiddenInput())
    visibility = forms.TypedChoiceField(
        label=_("可见性"),
        initial=0,
        coerce=int,
        choices=VISIBILITY_CHOICES,
        widget=forms.RadioSelect,
    )

common/views.py
from django.shortcuts import render
from group.models import Group, Topic, Comment
from users.models import User


def home(request):
    groups = Group.objects.order_by('-id')
    my_groups = []
    my_groups_topics = []
    my_groups_comments = []
    last_topics = Topic.objects.order_by('-id')[:20]
    last_join_users = User.objects.order_by('-id')[:20]
    last_comments = Comment.objects.order_by('-id')[:20]
    if request.user.is_authenticated:
        my_groups = request.user.groupmember_set.order_by('-id')
        my_groups_topics = Topic.objects.filter(group__in=my_groups.values('group_id')).order_by('-id')[:20]
        my_groups_comments = Comment.objects.filter(topic__group__in=my_groups.values('group_id')).order_by('-id')[:20]

    return render(request, 'group/home.html', {
            'groups_lists': [([g.group for g in my_groups], '我加入的小组'), (groups, '全部小组')],
            'my_groups_topics': my_groups_topics, 'last_topics': last_topics,
            'my_groups_comments': my_groups_comments, 'last_comments': last_comments,
            'last_join_users': last_join_users,
    })

common/templates/partial/_announcement.html
{% load static %}
{% load i18n %}
{% load admin_url %}
{% load mastodon %}
{% load oauth_token %}
{% load truncate %}
{% load thumb %}
<div id="modals">
    <style>
        .bottom-link {
            margin-top: 30px; text-align: center; margin-bottom: 5px;
        }
        .bottom-link a {
            color: #ccc;
        }
    </style>
    <div class="announcement-modal modal">
        <div class="announcement-modal__head">
            <h4 class="announcement-modal__title">{% trans '公告' %}</h4>
    
            <span class="announcement-modal__close-button modal-close">
                <span class="icon-cross">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                        <polygon
                            points="20 2.61 17.39 0 10 7.39 2.61 0 0 2.61 7.39 10 0 17.39 2.61 20 10 12.61 17.39 20 20 17.39 12.61 10 20 2.61">
                        </polygon>
                    </svg>
                </span>
            </span>
        </div>
        <div class="announcement-modal__body">
            <ul>
                {% for ann in unread_announcements %}
                    <li class="announcement">
                        <a href="{% url 'management:retrieve' ann.pk %}">
                            <h5 class="announcement__title">{{ ann.title }}</h5>
                        </a>
                        <span class="announcement__datetime">{{ ann.created_time }}</span>
                        <p class="announcement__content">{{ ann.get_plain_content | truncate:200 }}</p>
                    </li>
                    {% if not forloop.last %}
                        <div class="dividing-line" style="border-top-style: dashed;"></div>
                    {% endif %}
                {% endfor %}
            </ul>
            <div class="bottom-link">
                <a href="{% url 'management:list' %}">{% trans '查看全部公告' %}</a>
            </div>
        </div>
    </div>
</div>
<div class="bg-mask"></div>
<script>
    // because the modal and mask elements only exist when there are new announcements
    $(".announcement-modal").show();
    $(".bg-mask").show();
    $(".modal-close").on('click', function () {
        $(this).parents(".modal").hide();
        $(".bg-mask").hide();
    });
</script>

common/templates/partial/_footer.html
<footer class="footer">
    <div class="grid">
        <div class="footer__border">
            {% if social_link %}
            <a class="footer__link" target="_blank" href="{{ social_link }}">关注我们</a>
            {% endif %}
            {% if support_link %}
            <a class="footer__link" target="_blank" href="{{ support_link }}">问题反馈</a>
            {% endif %}
            <a class="footer__link" target="_blank" href="{{repo_link}}">Source</a>
            <a class="footer__link" target="_blank" href="{{matrix_link}}">Matrix</a>
            {% if donation_link %}
            <a class="footer__link" target="_blank" href="{{ donation_link }}">Donate</a>
            {% endif %}
        </div>
    </div>
</footer>


<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{google_analytics_id}}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{{google_analytics_id}}');
</script>

common/templates/partial/_navbar.html
{% load static %}
{% load i18n %}
{% load admin_url %}
<section id="navbar">
    <nav class="navbar">
        <div class="grid">
            <div class="navbar__wrapper">
                <a href="{% url 'common:home' %}" class="navbar__logo">
                    <img src="{% static 'img/logo.svg' %}" alt="" class="navbar__logo-img" width="32" height="32">
                </a>
                <button class="navbar__dropdown-btn">• • •</button>
                <ul class="navbar__link-list">

                    {% if request.user.is_authenticated %}
                        <a class="navbar__link {% if current == 'home' %}current{% endif %}" href="/">{% trans '主页' %}</a>
                        <a class="navbar__link" href="https://neodb.social/" target="_blank">{% trans '书影音' %}</a>
                        <a class="navbar__link" href="{% url 'group:create' %}">{% trans '创建小组' %}</a>
                        <a class="navbar__link" id="logoutLink" href="{% url 'users:logout' %}">{% trans '登出' %}</a>
                        {% if request.user.is_superuser %}
                        <a class="navbar__link" href="{% admin_url %}">{% trans '后台' %}</a>
                        {% endif %}

                    {% else %}
                        <a class="navbar__link" href="{% url 'users:login' %}?next={{ request.path }}">{% trans '登录' %}</a>
                    {% endif %}
                </ul>
            </div>

        </div>
    </nav>
</section>

common/templates/partial/_sidebar.html
{% load static %}
{% load i18n %}
{% load admin_url %}
{% load mastodon %}
{% load oauth_token %}
{% load truncate %}
{% load thumb %}

<div class="grid__aside grid__aside--reverse-order grid__aside--tablet-column">
    <div class="aside-section-wrapper aside-section-wrapper--no-margin">
        <div class="user-profile" id="userInfoCard">
            <div class="user-profile__header">
                <!-- <img src="" class="user-profile__avatar mast-avatar" alt="{{ user.username }}"> -->
                <img src="{{ user.mastodon_account.avatar }}" class="user-profile__avatar mast-avatar">
                <a href="">
                    <h5 class="user-profile__username mast-displayname">{{ user.mastodon_account.display_name }}</h5>
                </a>
                <!-- {{ user.id }} -->
            </div>
            <p><a class="user-profile__link mast-acct" target="_blank" rel="me" href="{{ user.mastodon_account.url }}">@{{ user.username }}@{{ user.mastodon_site }}</a>
                {% current_user_relationship user as relationship %}
                {% if relationship %}
                <a class="user-profile__report-link">
                    {{ relationship }}
                </a>
                {% endif %}
            </p>
            <p class="user-profile__bio mast-brief">{{ user.mastodon_account.note }}</p>

            {% if request.user != user %}
            <a href="{% url 'users:report' %}?user_id={{ user.id }}"
                class="user-profile__report-link">{% trans '投诉用户' %}</a>
            {% endif %}

        </div>
    </div>

    <div class="relation-dropdown">
        <div class="relation-dropdown__button">
            <span class="icon-arrow">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">
                    <path d="M8.12,3.29,5,6.42,1.86,3.29H.45L5,7.84,9.55,3.29Z" />
                </svg>
            </span>
        </div>

        {% if user == request.user %}
        <div class="relation-dropdown__body">
            <div class="aside-section-wrapper aside-section-wrapper--transparent aside-section-wrapper--collapse">
                <div class="user-relation" id="followings">
                    <h5 class="user-relation__label">
                        {% trans '关注的人' %}
                    </h5>
                    <a href="{% url 'users:following' user.mastodon_username %}"
                        class="user-relation__more-link mast-following-more">{% trans '更多' %}</a>
                    <ul class="user-relation__related-user-list mast-following">
                        <li class="user-relation__related-user">
                            <a>
                                <img src="" alt="" class="user-relation__related-user-avatar">
                                <div class="user-relation__related-user-name mast-displayname">
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>

                <div class="user-relation" id="followers">
                    <h5 class="user-relation__label">
                        {% trans '被他们关注' %}
                    </h5>
                    <a href="{% url 'users:followers' user.mastodon_username %}"
                        class="user-relation__more-link mast-followers-more">{% trans '更多' %}</a>
                    <ul class="user-relation__related-user-list mast-followers">
                        <li class="user-relation__related-user">
                            <a>
                                <img src="" alt="" class="user-relation__related-user-avatar">
                                <div class="user-relation__related-user-name mast-displayname">
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>

{% if user == request.user %}
<div id="oauth2Token" hidden="true">{{ request.user.mastodon_token }}</div>
<div id="mastodonURI" hidden="true">{{ request.user.mastodon_site }}</div>
<div id="userMastodonID" hidden="true">{{ user.mastodon_id }}</div>
<div id="userPageURL" hidden="true">{% url 'group:profile' 0 %}</div>

<div id="spinner" hidden>
    <div class="spinner">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>
{% endif %}