group/urls.py
from django.urls import path
from group.views import *
from group.feeds import LatestTopicsFeed
from django.contrib.auth.decorators import login_required


app_name = "group"
urlpatterns = [
    path("create/", login_required(create), name="create"),
    path("<int:group_id>/new_topic", login_required(new_topic), name="new_topic"),
    path("<int:group_id>/join", j_login_required(join), name="join"),
    path("<int:group_id>/leave", j_login_required(leave), name="leave"),
    path("<int:group_id>/group_edit", login_required(group_edit), name="group_edit"),
    path("<int:group_id>/topics", get_topics, name="topics"),
    path("<int:group_id>/", group, name="group"),
    path("topic/<int:topic_id>/", topic, name="topic"),
    path("topic/<int:topic_id>/comments", get_comments, name="comments"),
    path("topic/<int:topic_id>/delete", delete_topic, name="delete_topic"),
    path("comment/<int:comment_id>/delete", delete_comment, name="delete_comment"),
    path("comment/<int:comment_id>/like", j_login_required(like_comment), name="like_comment"),
    path("profile/<str:mastodon_username>/", profile, name="profile"),
    path("<int:group_id>/feed/", LatestTopicsFeed(), name="feed"),
]

neogroup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from users.views import login

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", login),
    path("markdownx/", include("markdownx.urls")),
    path("users/", include("users.urls")),
    path("group/", include("group.urls")),
    path("", include("common.urls")),
    path("tz_detect/", include("tz_detect.urls")),
]

# if settings.DEBUG:
    # from django.conf.urls.static import static
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

group/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from group.models import Group, Topic, Comment
from markdownx.fields import MarkdownxFormField


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ('id', 'title', 'description')
    title = forms.CharField(max_length=255, required=True, widget=forms.TextInput(attrs={'placeholder': _('添加标题')}))
    description = MarkdownxFormField(required=True)
    id = forms.IntegerField(required=False)
    share_to_mastodon = forms.BooleanField(
        label=_("分享到联邦网络"), initial=True, required=False
    )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('id', 'content')

    content = forms.CharField(required=True, widget=forms.Textarea(attrs={"rows": 5}))
    id = forms.IntegerField(required=False)
    comment_reply = forms.IntegerField(required=False, widget=forms.HiddenInput)
    share_to_mastodon = forms.BooleanField(
        label=_("分享到联邦网络"), initial=True, required=False
    )


class GroupSettingsForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('id', 'description', 'icon_url')
    description = forms.CharField(required=True, widget=forms.Textarea(attrs={"rows": 5}))
    id = forms.IntegerField(required=False, widget=forms.HiddenInput)

group/views.py
import json
from functools import wraps
from django.conf import settings
from django.urls import reverse
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.utils.translation import gettext_lazy as _
from django.views.decorators.http import require_http_methods
from mastodon.api import share_topic, share_comment
from common.config import ITEMS_PER_PAGE
from users.models import User
from group.models import Group, Topic, GroupMember, Comment, LikeComment
from group.forms import TopicForm, GroupSettingsForm


def success(msg="", data=None):
    return JsonResponse({"r": 0, "msg": msg, "data": data})


def error(msg):
    return JsonResponse({"r": 1, "msg": msg})


def render_relogin(request):
    return render(
        request,
        "common/error.html",
        {
            "url": reverse("users:connect") + "?domain=" + request.user.mastodon_site,
            "msg": _("信息已保存，但是未能分享到联邦网络"),
            "secondary_msg": _(
                "可能是你在联邦网络(Mastodon/Pleroma/...)的登录状态过期了，正在跳转到联邦网络重新登录😼"
            ),
        },
    )


def j_login_required(f):
    @wraps(f)
    def wrapper(request, *args, **kwargs):
        if not request.user.is_authenticated:
            return error("请先登录")
        return f(request, *args, **kwargs)
    return wrapper


def create(request):
    if request.method == "POST":
        name = request.POST["grp_name"].strip()
        description = request.POST["grp_content"]
        if name and description:
            group = Group()
            group.user = request.user
            group.name = name
            group.description = description
            group.save()
            GroupMember.objects.create(user=request.user, group=group)
            return redirect("group:group", group_id=group.id)
        else:
            return render(
                request,
                "common/error.html",
                {
                    "msg": "必须填写小组名称和小组简介",
                    "secondary_msg": "",
                },
            )
    return render(request, "group/create.html", {"site_name": settings.SITE_INFO["site_name"]})


def group(request, group_id):
    group = Group.objects.filter(id=group_id).first()
    if not group:
        return render(
            request,
            "common/error.html",
            {
                "msg": "小组不存在",
                "secondary_msg": "",
            },
        )
    page = int(request.GET.get("page", 1))
    page_size = ITEMS_PER_PAGE
    start = (page-1)*page_size

    last_join_users = [u.to_json()
                       for u in group.groupmember_set.order_by("-id")[:8]]
    last_topics = [t.to_json() for t in group.topic_set.order_by(
        "-id")[start: start+page_size]]
    is_member = GroupMember.is_member(
        request.user, group) if request.user.is_authenticated else False

    group_props = {
        "group": group.to_json(),
        "is_member": is_member,
        "last_topics": last_topics,
        "page_size": page_size,
        "page": page,
        "total": group.topic_set.count()
    }
    operations = []
    if request.user == group.user:
        operations = [
            [f"/group/{group.id}/group_edit", '小组管理'],
        ]

    sidebar_props = {
        "last_join_users": last_join_users,
        "operations": operations
    }

    nav_props = {
        "title": group.display_name,
    }

    return render(request, "group/group.html", {
        "title": group.display_name,
        "nav_props": nav_props,
        "group_props": group_props,
        "sidebar": sidebar_props,
        "group": group
    })


def get_topics(request, group_id):
    group = Group.objects.filter(id=group_id).first()
    if not group:
        return error("小组不存在")
    page = request.GET.get("page") or 1
    per_page = ITEMS_PER_PAGE
    start = (int(page) - 1) * per_page

    topics = [t.to_json()
              for t in group.topic_set.order_by("-id")[start:start + per_page]]
    return success(data=topics)


def new_topic(request, group_id):
    topic_group = Group.objects.filter(id=group_id).first()
    if not topic_group:
        return render(
            request,
            "common/error.html",
            {
                "msg": "小组不存在",
                "secondary_msg": "",
            },
        )

    is_member = GroupMember.is_member(
        request.user, topic_group) if request.user.is_authenticated else False

    if request.method == "POST":
        if not is_member:
            return error("你不是小组成员，不能参与话题讨论")

        data = json.loads(request.body)
        title = data.get("title")
        description = data.get("content")
        if not title or not description:
            return error("标题和内容不能为空")

        topic = Topic.objects.create(
            user=request.user,
            title=title.strip(),
            description=description,
            group=topic_group,
        )
        topic.type = 0
        topic.save()
        if data.get("share_to_mastodon"):
            topic.save = lambda **args: None
            topic.shared_link = None
            share_topic(topic)

        return success(
            data={
                'redirect_uri': topic.absolute_url
            }
        )

    if not is_member:
        return render(
            request,
            "common/error.html",
            {
                "msg": "你不是小组成员，不能参与话题讨论",
                "secondary_msg": "",
            },
        )

    return render(request, "group/react_new_topic.html", {
        "group": topic_group,
        "title": "在%s发新帖" % topic_group.display_name,
        "submit_api": "/group/%s/new_topic" % topic_group.id,
        "nav_props": {
            "title":  "在%s发新帖" % topic_group.display_name},
    })


def topic(request, topic_id):
    topic = Topic.objects.filter(id=topic_id).first()
    is_member = GroupMember.is_member(
        request.user, topic.group) if request.user.is_authenticated else False
    if not topic:
        return render(
            request,
            "common/error.html",
            {
                "msg": "话题不存在",
                "secondary_msg": "",
            },
        )
    if request.method == "POST":
        if not is_member:
            return error("你不是小组成员，不能参与话题讨论")

        data = json.loads(request.body.decode('utf-8'))
        comment_reply_id = data.get("comment_reply")
        content = data.get("content")
        comment_reply = None
        if not content:
            return error("评论内容不能为空")

        if comment_reply_id:
            comment_reply = Comment.objects.filter(id=comment_reply_id).first()
        comment = Comment.objects.create(
            user=request.user,
            topic=topic,
            content=content,
            comment_reply=comment_reply,
        )
        topic.updated_at = comment.created_at
        topic.save()

        if data.get("share_to_mastodon"):
            # TODO If there is a comment_reply field, it should be at the corresponding user in mastodon
            comment.save = lambda **args: None
            comment.shared_link = None
            if not share_comment(comment):
                # FIXME: ajax need_login attention
                return render_relogin(request)

        return success()

    comment_id = request.GET.get("comment_id")
    page = int(request.GET.get("page", 1))
    page_size = ITEMS_PER_PAGE
    total = Comment.objects.filter(topic=topic).count()
    # get page index by comment_id
    if comment_id:
        comment = Comment.objects.filter(topic=topic, id=comment_id).first()
        if comment:
            index = list(topic.comment_set.order_by(
                "id").values_list('id', flat=True)).index(comment.id)
            page = index // page_size + 1

    comments = topic.get_comments_dict(
        request.user, (page-1)*page_size, page_size)

    last_topics = [t.to_json()
                   for t in topic.group.topic_set.order_by("-id")[:5]]

    topic_props = topic.to_json()
    topic_group = topic.group

    topic_props.update({
        "comments": comments,
        "is_member": is_member,
        "page": page,
        "page_size": page_size,
        "total": total,
    })

    sidebar_props = {
        "last_topics": last_topics,
        "group": topic_group.to_json()
    }

    nav_props = {
        "card": {
            "url": topic_group.absolute_url,
            "icon": str(topic_group.icon_url),
            "name": topic_group.display_name,
        },
        "title": topic.title,
    }

    return render(request, "group/topic.html", {
        "title": topic.title,
        "topic": topic_props,
        "sidebar": sidebar_props,
        "nav_props": nav_props
    })


def get_comments(request, topic_id):
    topic = Topic.objects.filter(id=topic_id).first()
    if not topic:
        return error("话题不存在")
    page = request.GET.get("page") or 1
    per_page = ITEMS_PER_PAGE
    start = (int(page) - 1) * per_page

    comments = topic.get_comments_dict(request.user, start, per_page)
    return success(data=comments)


def delete_topic(request, topic_id):
    topic = Topic.objects.filter(id=topic_id).first()
    if not topic:
        return render(
            request,
            "common/error.html",
            {
                "msg": "话题不存在",
                "secondary_msg": "",
            },
        )
    if request.user != topic.user:
        return render(
            request,
            "common/error.html",
            {
                "msg": "你不是话题作者，不能删除话题",
                "secondary_msg": "",
            },
        )
    if topic.comment_set.count() > 0:
        return render(
            request,
            "common/error.html",
            {
                "msg": "话题有评论，不能删除",
                "secondary_msg": "",
            },
        )
    topic.delete()
    return redirect("group:group", group_id=topic.group.id)


def delete_comment(request, comment_id):
    comment = Comment.objects.filter(id=comment_id).first()
    if not comment:

group/templates/group/base.html
{% load static %}
{% load i18n %}
{% load admin_url %}
{% load mastodon %}
{% load oauth_token %}
{% load truncate %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="/favicon.svg">
    {% block extra_head %}
    <meta property="og:title" content="{{ site_name }}">
    <meta property="og:description" name="description" content="{{ site_name }}致力于为联邦宇宙居民提供一个自由、开放、互联的小组产品">
    {% endblock %}
    <meta property="og:type" content="website">
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'img/logo_square.png' %}">

    <title>{{ site_name }} - {%block title%}{%endblock%}</title>

    {% include "libs/common.html" with jquery=1 %}

    <script src="{% static 'js/mastodon.js' %}" defer></script>
    <script src="{% static 'js/home.js' %}" defer></script>
</head>

<body>
<div id="page-wrapper">
    <div id="content-wrapper">
        {% include "partial/_navbar.html" with current="home" %}
        <section id="content">
            <div class="grid grid--reverse-order">
                <div class="grid__main grid__main--reverse-order">
                    <div class="main-section-wrapper sortable">
                        {%block content%}
                        {%endblock%}
                    </div>
                </div>
                {% block sidebar %}
                {% endblock %}
            </div>
        </section>
    </div>
    {% include "partial/_footer.html" %}
</div>

</body>
</html>

group/templates/group/create.html
{% extends "group/base.html" %}
{% block title %}申请创建小组{% endblock %}

{% block content %}
<h1>创建小组</h1>
<div class="grid-16-8 clearfix">
    <div class="article">
        <form id="site-form" name="lzform" method="post" class="basic-form">{% csrf_token %}
            <div style="display:none;"><input type="hidden" name="ck" value="nyRj"/></div>
            <input type="hidden" name="site_type" value="P"/>

            <div class="field">
                <label class="field-label">小组名称:</label>
                <div class="item fix-validate" style="padding-bottom: 25px;">
                    <input name="grp_name" type="text"  maxlength="63" value="" class="basic-input"/>
                    <span class="validate-option-always-visible">小组名称代表小组主要讨论主题，鲜明、独特的组名有助于提高小组的辨识度，例如：吃喝玩乐在北京，就是一个很好的名字</span>
                </div>
            </div>

            <div class="field">
                <label class="field-label">小组简介:</label>
                <div class="item baseline-item fix-validate" style="padding-bottom: 20px;">
                    <textarea name="grp_content" type="text"  rows="15" cols="50" value="" class="basic-textarea"></textarea>
                    <span class="validate-option-always-visible">详细介绍小组的主题、用法与发言规则，帮助新成员快速了解、融入你的小组</span>
                </div>
            </div>

            <div class="form-actions">
                <input type="hidden" name="step_submit" value="on">
                <input class="btn-submit" type="submit" value="提交"/>
            </div>
        </form>
    </div>
</div>
{% endblock %}

group/templates/group/group.html
{% extends "group/react_base.html" %}
{% block extra_head %}
<meta property="og:title" content="{{group.name}}">
<meta property="og:description" name="description" content="{{group.description | truncatechars:100}}">
<link rel="alternate" type="application/rss+xml" title="{{group.name}} RSS" href="{% url 'group:feed' group.id %}" />
{% endblock %}

{% load react %}
{% load static %}

{% block main %}
{% react_render component="Group" props=group_props no_placeholder=1 %}
{% endblock %}

{% block sidebar %}
{% react_render component="GroupSidebar" props=sidebar no_placeholder=1 %}
{% endblock %}

group/templates/group/group_edit.html
{% extends "group/base.html" %}

{% block title %}{{group.name}}{% endblock %}

{% block content %}
<form method="post" class="group-form" enctype="multipart/form-data">{% csrf_token %}
    {{ form }}
    <input type="submit" value="提交" />
</form>
{% endblock %}

group/templates/group/home.html
{% extends "group/base.html" %}
{% block title %}Home{% endblock %}

{% block content %}
{% load thumb %}

{% if my_groups_topics %}
<div>
    <h5>我加入的小组最新帖子</h5>
    <ul>
        {% for topic in my_groups_topics %}
        <li>
        <a href="{% url 'group:topic' topic.id %}">{{topic.title}}</a> - from <a href="{% url 'group:group' topic.group.id %}">{{topic.group.name}}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<div class="dividing-line"></div>
{% endif %}

{% if my_groups_comments %}
<div>
    <h5>我加入的小组最新回复</h5>
    <ul>
        {% for comment in my_groups_comments %}
        <li>
        <a href="{{ comment.absolute_url }}">{{comment.content | truncatechars:40}}</a> - from <a href="{% url 'group:group' comment.topic.group.id %}">{{comment.topic.group.name}}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<div class="dividing-line"></div>
{% endif %}

{% for gl in groups_lists %}
    {% if gl.0 %}
        <div>
            <h5>{{gl.1}}</h5>
            <ul>
            {% for g in gl.0 %}
                <li style="font-size: 16px;display: flex">
                {% if g.icon_url %}
                    <div style="flex: 0 0 auto;margin-right: 15px">
                        <img width="64" height="64" src="{{g.icon_url|thumb:'group'}}" class="entity-detail__avatar">
                    </div>
                {% endif %}
                    <div style="align-self: center">
                        <a href="{% url 'group:group' g.id %}">{{g.name}}</a>
                        - {{g.description | truncatechars:40}}
                    </div>
                </li>
            {% endfor %}
            </ul>
        </div>
        <div class="dividing-line"></div>
    {% endif %}
{% endfor %}

<div>
    <h5>最新帖子</h5>
    <ul>
        {% for topic in last_topics %}
        <li>
        <a href="{% url 'group:topic' topic.id %}">{{topic.title}}</a> - from <a href="{% url 'group:group' topic.group.id %}">{{topic.group.name}}</a>
        </li>
        {% endfor %}
    </ul>
</div>

<div class="dividing-line"></div>
<div>
    <h5>最新回复</h5>
    <ul>
        {% for comment in last_comments %}
        <li>
        <a href="{{ comment.absolute_url }}">{{comment.content}}</a> - from <a href="{% url 'group:profile' comment.user.mastodon_username %}">{{comment.user.mastodon_username}}</a>
        </li>
        {% endfor %}
    </ul>
</div>

<div class="dividing-line"></div>
<div>
    <h5>最新加入的用户</h5>
    <ul>
        {% for user in last_join_users %}
        <li>
        <img width="32" height="32" src="{{ user.mastodon_account.avatar }}" class="user-profile__avatar mast-avatar">
        <a href="{% url 'group:profile' user.mastodon_username %}">{{user.mastodon_username}}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

{% block sidebar %}
    {% if request.user.is_authenticated %}
    {%include "partial/_sidebar.html"%}
    {% endif %}
{% endblock %}

group/templates/group/new_topic.html
{% extends "group/base.html" %}
{% block title %}{{group.name}}{% endblock %}

{% block content %}
{% load static %}
<script>
    $(document).ready( function() {

    $(".markdownx-preview").hide();
    $(".markdownx textarea").attr("placeholder", "从剪贴板粘贴或者拖拽文件至编辑框即可插入图片");

    $(".topic-form__preview-button").on('click', function() {
        if ($(".markdownx-preview").is(":visible")) {
            $(".topic-form__preview-button").text("预览");
            $(".markdownx-preview").hide();
            $(".markdownx textarea").show();
        } else {
            $(".topic-form__preview-button").text("编辑");
            $(".markdownx-preview").show();
            $(".markdownx textarea").hide();
        }
    });
});
</script>
<form method="post" class="review-form">{% csrf_token %}
    {{ form.title }}
    <span class="float-right">
        <span class="topic-form__preview-button">预览</span>
    </span>
    <div id="rawContent">
    {{ form.description }}
    </div>
    <div class="review-form__share-checkbox">
        {{ form.share_to_mastodon }}{{ form.share_to_mastodon.label }}
    </div>
<input type="submit" value="提交" />
<script src="{% static 'markdownx/js/markdownx.min.js' %}"></script>
</form>
{% endblock %}

{% block sidebar %}
{% include "group/sidebar_group.html" %}
{% endblock %}

{% block footer %}
{% include "group/footer.html" %}
{% endblock %}

group/templates/group/profile.html
{% extends "group/base.html" %}
{% block title %}{{user.mastodon_username}}{% endblock %}

{% block content %}
    <div>
    <img width="64" height="64" src="{{ user.mastodon_account.avatar }}" class="user-profile__avatar mast-avatar">
    <h5>{{user.mastodon_username}}</h5>
    </div>

    <h5>加入的小组</h5>
    <ul>
    {% for jg in join_groups %}
    <li><a href="{% url 'group:group' jg.group.id %}">{{jg.group.name}}</a></li>
    {% endfor %}
    </ul>

    <div class="dividing-line"></div>
    <h5>最新帖子</h5>
    <ul>
    {% for topic in topics %}
    <li><a href="{% url 'group:topic' topic.id %}">{{topic.title}}</a> - {{topic.updated_at}}</li>
    {% endfor %}
    </ul>

    <div class="dividing-line"></div>
    <h5>最新回复</h5>
    <ul>
    {% for comment in comments %}
    <li><a href="{{ comment.absolute_url }}">{{comment.content}}</a> - {{comment.created_at}}</li>
    {% endfor %}
    </ul>
{% endblock %}

{% block sidebar %}
{% include "partial/_sidebar.html" %}
{% endblock %}

group/templates/group/react_group.html
{% extends "group/react_base.html" %}
{% block extra_head %}
<meta property="og:title" content="{{group.name}}">
<meta property="og:description" name="description" content="{{group.description | truncatechars:100}}">
<link rel="alternate" type="application/rss+xml" title="{{group.name}} RSS" href="{% url 'group:feed' group.id %}" />
{% endblock %}

{% load react %}
{% load static %}

{% block title %}
{{title}}小组
{% endblock %}

{% block content %}
{% react_render component="Group" props=group_props no_placeholder=1 %}
{% endblock %}

{% block sidebar %}
{% react_render component="GroupSidebar" props=sidebar no_placeholder=1 %}
{% endblock %}

group/templates/group/react_new_topic.html
{% extends "group/react_base.html" %}

{% load react %}
{% load static %}

{% block extra_head %}
<meta property="og:title" content="在{{group.name}}发言">
<meta property="og:description" name="description" content="{{group.description | truncatechars:100}}">
<link rel="stylesheet" href="{% static 'react/editor.css' %}">
{% endblock %}

{% block content %}
<div id="content">
    <div id="editor-wrapper">
    </div>
</div>

<script>
var CONFIG = {
    api: "{{  submit_api }}"
}
</script>
<script type="module" src="{% static 'react/editor.js' %}" ></script>
{% endblock %}

group/templates/group/react_topic.html
{% extends "group/react_base.html" %}
{% block extra_head %}
<meta property="og:title" content="{{topic.title}}">
<meta property="og:description" name="description" content="{{topic.description | truncatechars:100}}">
{% endblock %}

{% load react %}
{% load static %}

{% block title %}
{{topic.title}}
{% endblock %}

{% block content %}
{% react_render component="Topic" props=topic no_placeholder=1 %}
{% endblock %}

{% block sidebar %}
{% react_render component="TopicSidebar" props=sidebar no_placeholder=1 %}
{% endblock %}

group/templates/group/sidebar.html
{% load static %}
{% load i18n %}
{% load admin_url %}
{% load mastodon %}
{% load oauth_token %}
{% load truncate %}
{% load thumb %}
<style>
    ul.group-user__group-user-list {
        display:flex;
        list-style:none;
        flex-wrap: wrap;
    }
    li.group-user__user {
        text-align: center;
        justify-items: center;
        padding: 0 3px !important;
    }
</style>
<div class="grid__aside grid__aside--reverse-order grid__aside--tablet-column">
    <div class="relation-dropdown">
        <div class="relation-dropdown__button">
            <span class="icon-arrow">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">
                    <path d="M8.12,3.29,5,6.42,1.86,3.29H.45L5,7.84,9.55,3.29Z" />
                </svg>
            </span>
        </div>

        <div class="relation-dropdown__body">
            <div class="aside-section-wrapper aside-section-wrapper--transparent aside-section-wrapper--collapse">
                <div>
                    <h5>
                        {% trans '最近加入' %}
                    </h5>
                    <ul class="group-user__group-user-list">
                        {% for group_member in last_join_users %}
                        <li class="group-user__user">
                            <a href="{% url 'group:profile' group_member.user.mastodon_username %}">
                                <img width="32" height="32" src="{{ group_member.user.mastodon_account.avatar }}" class="user-profile__avatar mast-avatar" alt="{{group_member.user.mastodon_username}}">
                                <div class="user-name mast-displayname">
                                {{group_member.user.username}}
                                </div>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div>
                    <ul>
                    {% if group.user == request.user %}
                    <li>&gt; 成员管理</li>
                    <li>&gt; <a href="{% url 'group:group_edit' group.id %}">小组管理</a></li>
                    {% endif %}
                    {% if is_member %}
                    <li>&gt; <a href="{% url 'group:leave' group.id %}">退出小组</a></li>
                    {% endif %}
                    </ul>
                </div>
            </div>
        </div>

      </div>
  </div>

  {% if user == request.user %}
  <div id="oauth2Token" hidden="true">{{ request.user.mastodon_token }}</div>
  <div id="mastodonURI" hidden="true">{{ request.user.mastodon_site }}</div>
  <div id="userMastodonID" hidden="true">{{ user.mastodon_id }}</div>

  <div id="spinner" hidden>
    <div class="spinner">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
  </div>
  {% endif %}

group/templates/group/sidebar_group.html
{% load thumb %}
<div class="grid__aside grid__aside--reverse-order grid__aside--tablet-column">
    <div class="relation-dropdown">
        <div class="relation-dropdown__button">
            <span class="icon-arrow">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">
                    <path d="M8.12,3.29,5,6.42,1.86,3.29H.45L5,7.84,9.55,3.29Z" />
                </svg>
            </span>
        </div>

        <div class="relation-dropdown__body">
            <div class="aside-section-wrapper aside-section-wrapper--transparent aside-section-wrapper--collapse">
                <div class="user-relation" id="followings">
                    <img src="{{group.icon_url|thumb:'group'}}" class="entity-detail__avatar"><br>
                    <a href="{% url 'group:group' group.id %}">{{group.name}}</a>
                </div>
                <div class="dividing-line"></div>
                <div>
                    <h5>最新讨论</h5>
                    <ul>
                        {% for t in last_topics %}
                        <li><a href="{% url 'group:topic' t.id %}">{{t.title}}</a> ({{t.user.mastodon_username}})</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>

      </div>
  </div>

  {% if user == request.user %}
  <div id="oauth2Token" hidden="true">{{ request.user.mastodon_token }}</div>
  <div id="mastodonURI" hidden="true">{{ request.user.mastodon_site }}</div>
  <div id="userMastodonID" hidden="true">{{ user.mastodon_id }}</div>

  <div id="spinner" hidden>
    <div class="spinner">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
  </div>
  {% endif %}